### ISSUE TITLE
can you explain the checking time procedure of addon?

### ISSUE THREAD

**Issue by rezad1393** [schierla/sitedelta#1]
how does it check to see how long have passed.
also if I close firefox for more than the update interval then it checks at the exact beginning  next firefox lunch right?

**Comment by schierla** [comment]
Sorry for the late reply. 
SiteDelta uses the WebExtension `alarms` API (see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms) to be informed once the next scan time has been reached. 
When Firefox is closed, or the computer is in standby mode, the alarm will fire after restarting it. Then, all pages that should have been scanned in the meantime will be scanned sequentially, with a pause of 5 seconds in between.

**Comment by rezad1393** [comment]
late but informative and complete answer.
thank you.
