### ISSUE TITLE
"Pages that failed to load" upon re-activation of Windows

### ISSUE THREAD

**Issue by strawbeard** [schierla/sitedelta#2]
When I **re-activate** Windows 10 from **hibernation** SiteDelta very often signals _"Pages that failed to load"_. Then I chose `Rescan` and almost always **no changes** are detected. Obviously, SiteDelta accesses the internet **before** the connection is ready (re-established). Maybe a simple delay will cure this condition (just guessing;-)

**Comment by schierla** [comment]
Thanks for the suggestion, it's definitely worth a try. Included in 0.25.4.

**Comment by strawbeard** [comment]
Problem fixed with version 0.25.4. Thank you very much!
